# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-14 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='boards',
            new_name='board',
        ),
    ]
